apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- ../../base
namePrefix: dev-
nameSuffix: -v1
namespace: dev


# Patch replace image blue to yellow
patches:
  - path: deployment.yaml


# Patch add ingress host json
#patches:
#- path: ingress-patch.json
#  target:
#    kind: Ingress
#    name: devops-ingress-nginx

