apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-ingress-blue-deployment
  labels:
    app.kubernetes.io/name: devops-ingress-blue
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: devops-ingress-blue
  template:
    metadata:
      labels:
        app.kubernetes.io/name: devops-ingress-blue
        app.kubernetes.io/version: 1.0.0
    spec:
      containers:
      - name: devops-blue
        image: timpamungkas/devops-blue:1.0.0
        resources:
          limits:
            cpu: "0.5"
            memory: 500M
        ports:
        - name:  http
          containerPort: 8111
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /devops/blue/actuator/health/readiness
            port: 8111
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 5
        livenessProbe:
          httpGet:
            path: /devops/blue/actuator/health/liveness
            port: 8111
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 5
  replicas: 1