apiVersion: v1
kind: Service
metadata:
  name: devops-blue-server
  labels:
    app.kubernetes.io/name: devops-ingress-blue
spec:
  selector:
    app.kubernetes.io/name: devops-ingress-blue
  ports:
  - port: 8111
    name: http