apiVersion: v1
kind: Service
metadata:
  namespace: devops
  name: devops-configmap-service
  labels:
    app.kubernetes.io/name: devops-configmap
spec:
  selector:
    app.kubernetes.io/name: devops-configmap
  type:  LoadBalancer
  ports:
  - port: 9011         # port number to be available at host
    targetPort: 8111   # port on pod